- hosts: all
  become: yes
  roles:
    - common
    - containerd
    - kubernetes

- hosts: control
  become: yes
  roles:
    - control-plane
    - app

- hosts: worker
  become: yes
  roles:
    - worker
